#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PaperHangMan.Resource", IsApplication=true)]

namespace PaperHangMan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowright = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GameBackground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gradient_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient_bg_hover = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Hangman_1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Hangman_2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Hangman_3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Hangman_4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Hangman_5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hangman_6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Hangman_7 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Hangman_8 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Hangman_9 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int HangmanLogo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int list_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int paperBackground = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int SplashScreen = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int btnLeaderboard = 2131099691;
			
			// aapt resource value: 0x7f060008
			public const int btnLetterA = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btnLetterB = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btnLetterC = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int btnLetterD = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnLetterE = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int btnLetterF = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int btnLetterG = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnLetterH = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int btnLetterI = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int btnLetterJ = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int btnLetterK = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int btnLetterL = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int btnLetterM = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int btnLetterN = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int btnLetterO = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int btnLetterP = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int btnLetterQ = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnLetterR = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btnLetterS = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int btnLetterT = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnLetterU = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btnLetterV = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int btnLetterW = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int btnLetterX = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int btnLetterY = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int btnLetterZ = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int btnMulti = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int btnQuit = 2131099692;
			
			// aapt resource value: 0x7f060026
			public const int btnReturn = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int btnSingle = 2131099689;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int lblScore = 2131099650;
			
			// aapt resource value: 0x7f060028
			public const int lblTitle = 2131099688;
			
			// aapt resource value: 0x7f060003
			public const int lblTotalLetters = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int lbltitle = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout2 = 2131099662;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout3 = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout4 = 2131099677;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout5 = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int linearLayoutWord = 2131099653;
			
			// aapt resource value: 0x7f060027
			public const int listView1 = 2131099687;
			
			// aapt resource value: 0x7f060000
			public const int sqlite_id = 2131099648;
			
			// aapt resource value: 0x7f060025
			public const int textView1 = 2131099685;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HangmanGame = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HangmanSplash = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LeaderboardDesign = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Promt = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SelectWord = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
